apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: seldon
spec:
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: @IMAGE_URL@:@IMAGE_TAG@
          #image-registry.openshift-image-registry.svc:5000/user1-stage/pipeline-s2i-test:latest
          imagePullPolicy: Always
          name: classifier
          livenessProbe:            
            httpGet:
              path: /health/status
              port: http
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /health/status
              port: http
              scheme: HTTP
    graph:
      children: []
      endpoint:
        type: REST
      name: classifier
      type: MODEL
    name: pred1
    annotations:
      predictor_version: v1
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: seldon
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: seldon-pred1
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
