apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: seldon-model
spec:
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/user1/pipeline-s2i-test:latest
          imagePullPolicy: Always
          name: seldon-model
    graph:
      children: []
      endpoint:
        type: REST
      name:  seldon-model
      type: MODEL
    name: pred1
    annotations:
      predictor_version: v1
